// @ts-check
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import tseslint from 'typescript-eslint';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// `eslint-config-next` still ships as a legacy .eslintrc-shaped config,
// and its dependency chain (eslint-plugin-import et al.) currently caps
// peer support at ESLint ^9.0.0 — the same documented exception
// docs/architecture/tech-stack.md already makes for apps/mobile and
// apps/api (each pins the ESLint major its own first-party CLI
// generates/tests against, rather than the packages/* catalog's ESLint
// 10). apps/web's package.json pins `eslint: 9.39.4` accordingly.
// FlatCompat bridges the legacy config shape into this flat config
// rather than hand-reimplementing Next's rule set.
const compat = new FlatCompat({ baseDirectory: __dirname });

export default tseslint.config(
  {
    // next-env.d.ts is auto-generated by the Next.js CLI on every dev/build
    // run and always contains a triple-slash reference — linting it is
    // linting Next's own generated code, not this project's.
    ignores: ['.next/**', 'out/**', 'node_modules/**', '.turbo/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
);
